### ISSUE TITLE
Not work 1.15.2 PAPER

### ISSUE THREAD

**Issue by bladbl** [UtechtDustin/Builder-s-Wand#46]
`ERROR 12:51:05
Error occurred while enabling BuildersWand v2.12.0 (Is it up to date?)
Console 12:51:05
java.lang.NullPointerException: null
at de.False.BuildersWand.manager.WandManager.addDefault(WandManager.java:124) ~[?:?]
at de.False.BuildersWand.manager.WandManager.load(WandManager.java:134) ~[?:?]
at de.False.BuildersWand.Main.loadConfigFiles(Main.java:97) ~[?:?]
at de.False.BuildersWand.Main.onEnable(Main.java:56) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-245]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1854) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1662) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1148) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-245]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by UtechtDustin** [comment]
I stopped working on that project.

**Comment by UtechtDustin** [comment]
The plugin is written for spigot.
