### ISSUE TITLE
broken Durability

### ISSUE THREAD

**Issue by mohmedXM** [UtechtDustin/Builder-s-Wand#60]
Builders Wand 2.18.1
both the Durability and the Durability text

the console error after make a 3-5 builds with the wand
```
[22:09:20] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BuildersWand v2.18.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:437) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:431) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [custom.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NumberFormatException: For input string: "201919191920"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_291]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_291]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_291]
        at de.False.BuildersWand.events.WandEvents.getDurability(WandEvents.java:897) ~[?:?]
        at de.False.BuildersWand.events.WandEvents.removeDurability(WandEvents.java:353) ~[?:?]
        at de.False.BuildersWand.events.WandEvents.playerInteract(WandEvents.java:227) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[custom.jar:git-Spigot-cbd1a1b-009d8af]
        ... 19 more
```
 
```
 wands:
  '1':
    name: '&3Builder Wand &e- &7Tier &c1'
    material: BLAZE_ROD
    maxSize: 16
    consumeItems: true
    durability:
      amount: 20
      enabled: true
      text: '&fDurability: {durability} / 20'
    crafting:
      ingredient:
        d: DIAMOND
        b: BLAZE_ROD
      enabled: false
      shapeless: false
      recipe:
      - xxd
      - xbx
      - bxx
    particles:
      enabled: true
      type: FLAME
      count: 1
    storage:
      enabled: false
      size: 27
```
![image](https://user-images.githubusercontent.com/52118994/120232873-239a6480-c25d-11eb-9185-6f76d4bd8e02.png)

![image](https://user-images.githubusercontent.com/52118994/120233010-77a54900-c25d-11eb-89c9-c46503f6e7e8.png)

**Comment by UtechtDustin** [comment]
I know the reason behind that issue, but its not that hard to fix.
As workaround until it's fixed, please prevent using additional numbers in the durability text.

**Comment by ProfessionalBoatDrifter** [comment]
Yeah I had the same issue. Good thing I found this on Github for the cause lol.

Is there an ETA on when this will be fixed? It's been a long time @UtechtDustin

**Comment by UtechtDustin** [comment]
Fixed in the newest version (4.0.0)
