### ISSUE TITLE
I think NMS Issue

### ISSUE THREAD

**Issue by xIrinaShaykx** [UtechtDustin/Builder-s-Wand#64]
[17:07:42] [Server thread/ERROR]: Error occurred while enabling BuildersWand v2.18.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.False.BuildersWand.NMS.NMS.getDefaultParticle()" because "this.nms" is null
        at de.False.BuildersWand.manager.WandManager.addDefault(WandManager.java:126) ~[?:?]
        at de.False.BuildersWand.manager.WandManager.load(WandManager.java:136) ~[?:?]
        at de.False.BuildersWand.Main.loadConfigFiles(Main.java:102) ~[?:?]
        at de.False.BuildersWand.Main.onEnable(Main.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by UtechtDustin** [comment]
The Builders wand currently dont support 1.17.
I will update it as soon i have some spare time.

**Comment by xIrinaShaykx** [comment]
ohhh didnt notice sry

**Comment by UtechtDustin** [comment]
No problem :)

**Comment by UtechtDustin** [comment]
Updated the Builders-Wand to 1.17 :-)
